set -g default-terminal 'screen-256color'

set -g pane-border-style 'fg=colour240'
set -g pane-active-border-style 'fg=colour36'

# set -g status-style 'bg=colour17 fg=colour69'
# setw -g window-status-style 'bg=colour17 fg=colour72'
# setw -g window-status-current-style 'bg=colour69 fg=colour17'

set -g status-style 'bg=colour245 fg=colour235'
setw -g window-status-style 'bg=colour52 fg=colour209'
setw -g window-status-current-style 'bg=colour202 fg=colour16'
